# Generated by Django 5.0.1 on 2024-11-14 12:30

import django.db.models.deletion
import railway.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_name", models.CharField(max_length=100)),
                ("passenger_age", models.IntegerField()),
                ("passenger_gender", models.CharField(max_length=10)),
                ("passenger_type", models.CharField(max_length=20)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "booking_passenger",
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Solved", "Solved")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("solved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "railway_query",
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=10, unique=True)),
                ("train_name", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        default=railway.models.generate_reference_number,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("train_number", models.CharField(max_length=10)),
                ("train_name", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "travel_class",
                    models.CharField(
                        choices=[("AC", "AC"), ("Non-AC", "Non-AC")], max_length=6
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("service_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=100)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("passenger_name", models.CharField(max_length=100)),
                ("passenger_age", models.IntegerField()),
                ("passenger_gender", models.CharField(max_length=10)),
                ("passenger_type", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Cancelled", "Cancelled")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="railway.passenger",
                    ),
                ),
            ],
            options={
                "db_table": "booking_booking",
            },
        ),
    ]
