# Generated by Django 5.0.1 on 2024-11-14 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="passenger",
        ),
        migrations.DeleteModel(
            name="Passenger",
        ),
    ]
