# Generated by Django 5.0.1 on 2024-11-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0003_alter_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
