# Generated by Django 5.0.1 on 2024-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0004_alter_booking_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="arrival_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="departure_time",
            field=models.TimeField(),
        ),
    ]
