# Generated by Django 5.0.1 on 2024-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0006_alter_booking_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="arrival_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="departure_time",
            field=models.DateTimeField(),
        ),
    ]
