# Generated by Django 5.0.1 on 2024-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0007_alter_booking_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="arrival_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
