# Generated by Django 5.0.1 on 2024-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0008_alter_booking_amount_paid_alter_train_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="arrival_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
