# Generated by Django 5.0.1 on 2024-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0009_alter_train_arrival_time_alter_train_departure_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="amount_paid",
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
