# Generated by Django 5.0.1 on 2024-12-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0010_remove_booking_amount_paid_booking_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="train",
            field=models.ForeignKey(
                default=12511,
                on_delete=django.db.models.deletion.CASCADE,
                to="railway.train",
            ),
        ),
    ]
