# Generated by Django 5.0.1 on 2024-12-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0011_booking_train"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="train",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="railway.train",
            ),
        ),
    ]
