# Generated by Django 5.0.1 on 2024-12-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0012_alter_booking_train"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="arrival_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
