# Generated by Django 5.0.1 on 2024-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0013_alter_booking_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="passenger_age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
