# Generated by Django 5.0.1 on 2024-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0017_alter_booking_passenger_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="passenger_age",
            field=models.IntegerField(null=True),
        ),
    ]
