# Generated by Django 5.0.1 on 2024-12-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0018_alter_booking_passenger_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="railway.train"
            ),
        ),
    ]
