# Generated by Django 5.0.1 on 2024-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway", "0019_alter_booking_train"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="number_of_tickets",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
